# vim: ft=yaml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Include:
    - "**/*.rb"
    - "**/*.gemspec"
    - "**/Gemfile"
    - "**/Rakefile"
  Exclude:
    - bin/**/*
    - db/schema.rb
    - spec/dummy/**/*
    - vendor/**/*
  NewCops: enable

# ---------------------------------------------------------------------------
#                                   Layout
# ---------------------------------------------------------------------------

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true
  SupportedStyles:
    - case
    - end

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# ---------------------------------------------------------------------------
#                                   Lint
# ---------------------------------------------------------------------------

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

# ---------------------------------------------------------------------------
#                                   Metrics
# ---------------------------------------------------------------------------

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# ---------------------------------------------------------------------------
#                                   RSpec
# ---------------------------------------------------------------------------

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

# ---------------------------------------------------------------------------
#                                   Style
# ---------------------------------------------------------------------------

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

# I do not like:
#
#     variable_name = if condition
#                       a
#                     else
#                       b
#                     end
#
# Therefore:
#
#     variable_name = begin
#       if condition
#         a
#       else
#         b
#       end
#     end
#
Style/RedundantBegin:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - spec/**/*_spec.rb

Style/TrivialAccessors:
  AllowPredicates: true
